spring:
  application:
    name: demo1
springdoc:
  swagger-ui:
    # ????????????? /swagger-ui.html
    path: /api-docs.html
    # ????????
    operations-sorter: alpha
  api-docs:
    # ????????
    path: /v3/api-docs
server:
  port: 8080